package it.betplus.birs.primitive;

// Generated 31-mar-2011 10.51.22 by Hibernate Tools 3.4.0.CR1

/**
 * Meterfact generated by hbm2java
 */
public class MeterfactGame extends Meterfact implements java.io.Serializable {

	private static final long serialVersionUID = 3228488180696302470L;

	public MeterfactGame() {
		super();
	}

	public void sumValue(MeterfactGame add) {

		this.setBet(add.getBet() + this.getBet());
		this.setWin(add.getWin() + this.getWin());
		this.setGamesPlayed(add.getGamesPlayed() + this.getGamesPlayed());
		this.setJackpotWins(add.getJackpotWins() + this.getJackpotWins());
		this.setJackpotContribution(add.getJackpotContribution()
				+ this.getJackpotContribution());
		this.setPreu(add.getPreu() + this.getPreu());
		this.setAams(add.getAams() + this.getAams());
		this.setNetWin(add.getNetWin() + this.getNetWin());
		this.setHouseWin(add.getHouseWin() + this.getHouseWin());
		this.setSupplierProfit(add.getSupplierProfit()
				+ this.getSupplierProfit());
		this.setOperatorsProfit(add.getOperatorsProfit()
				+ this.getOperatorsProfit());
		this.setBplusNetProfit(add.getBplusNetProfit()
				+ this.getBplusNetProfit());

	}

	public MeterfactGame clone() {

		MeterfactGame clone = new MeterfactGame();

		clone.setTempodim(this.getTempodim());
		clone.setSistemagiocodim(this.getSistemagiocodim());
		clone.setClientidim(this.getClientidim());
		clone.setSpaziodim(this.getSpaziodim());

		clone.setBet(this.getBet());
		clone.setWin(this.getWin());
		clone.setGamesPlayed(this.getGamesPlayed());
		clone.setJackpotWins(this.getJackpotWins());
		clone.setJackpotContribution(this.getJackpotContribution());
		clone.setPreu(this.getPreu());
		clone.setAams(this.getAams());
		clone.setNetWin(this.getNetWin());
		clone.setHouseWin(this.getHouseWin());
		clone.setSupplierProfit(this.getSupplierProfit());
		clone.setOperatorsProfit(this.getOperatorsProfit());
		clone.setBplusNetProfit(this.getBplusNetProfit());

		clone.setAamsJackpotId(this.getAamsJackpotId());

		return clone;
	}

}
