package it.betplus.birs.primitive;


// Generated 31-mar-2011 10.51.22 by Hibernate Tools 3.4.0.CR1


/**
 * Meterfact generated by hbm2java
 */
public abstract class Meterfact implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Double id;
	
	
	private Sistemagiocodim sistemagiocodim;
	private Tempodim tempodim;
	private Clientedim clientedim;
	private Spaziodim spaziodim;
	
	
	
	private Double bet = new Double(0);
	private Double win = new Double(0);
	private Long gamesPlayed = new Long(0);
	private Double jackpotWins = new Double(0);
	private Double jackpotContribution = new Double(0);
	private Double preu = new Double(0);
	private Double aams = new Double(0);
	private Double netWin = new Double(0);
	private Double houseWin = new Double(0);
	private Double supplierProfit = new Double(0); 
	private Double operatorsProfit = new Double(0);
	private Double bplusNetProfit = new Double(0);
	
	private boolean milionarie = false;
	private RealMillionvlt realMillionVlt;
	
	private Long aamsJackpotId;

	public Meterfact() {
		super();
	}

	public Double getId() {
		return this.id;
	}

	public void setId(Double id) {
		this.id = id;
	}

	public Sistemagiocodim getSistemagiocodim() {
		return this.sistemagiocodim;
	}

	public void setSistemagiocodim(Sistemagiocodim sistemagiocodim) {
		this.sistemagiocodim = sistemagiocodim;
	}

	public Tempodim getTempodim() {
		return this.tempodim;
	}

	public void setTempodim(Tempodim tempodim) {
		this.tempodim = tempodim;
	}

	public Clientedim getClientidim() {
		return this.clientedim;
	}

	public void setClientidim(Clientedim clientedim) {
		this.clientedim = clientedim;
	}

	public Spaziodim getSpaziodim() {
		return this.spaziodim;
	}

	public void setSpaziodim(Spaziodim spaziodim) {
		this.spaziodim = spaziodim;
	}

	public Double getBet() {
		return this.bet.doubleValue();
	}

	public void setBet(Double bet) {
		this.bet = bet;
	}

	public Double getWin() {
		return this.win.doubleValue();
	}

	public void setWin(Double win) {
		this.win = win;
	}

	public Long getGamesPlayed() {
		return this.gamesPlayed;
	}

	public void setGamesPlayed(Long gamesPlayed) {
		this.gamesPlayed = gamesPlayed;
	}

	public Double getJackpotWins() {
		return this.jackpotWins.doubleValue();
	}

	public void setJackpotWins(Double jackpotWins) {
		this.jackpotWins = jackpotWins;
	}

	public Double getJackpotContribution() {
		return this.jackpotContribution.doubleValue();
	}

	public void setJackpotContribution(Double jackpotContribution) {
		this.jackpotContribution = jackpotContribution;
	}

	public Double getPreu() {
		return this.preu.doubleValue();
	}

	public void setPreu(Double preu) {
		this.preu = preu;
	}

	public Double getAams() {
		return this.aams.doubleValue();
	}

	public void setAams(Double aams) {
		this.aams = aams;
	}

	public Double getNetWin() {
		return this.netWin.doubleValue();
	}

	public void setNetWin(Double netWin) {
		this.netWin = netWin;
	}

	public Double getHouseWin() {
		return this.houseWin.doubleValue();
	}

	public void setHouseWin(Double houseWin) {
		this.houseWin = houseWin;
	}

	public Double getSupplierProfit() {
		return this.supplierProfit.doubleValue();
	}

	public void setSupplierProfit(Double supplierProfit) {
		this.supplierProfit = supplierProfit;
	}

	public Double getOperatorsProfit() {
		return this.operatorsProfit.doubleValue();
	}

	public void setOperatorsProfit(Double operatorsProfit) {
		this.operatorsProfit = operatorsProfit;
	}

	public Double getBplusNetProfit() {
		return this.bplusNetProfit.doubleValue();
	}

	public void setBplusNetProfit(Double bplusNetProfit) {
		this.bplusNetProfit = bplusNetProfit;
	}


	public Long getAamsJackpotId() {
		return this.aamsJackpotId;
	}

	public void setAamsJackpotId(Long aamsJackpotId) {
		this.aamsJackpotId = aamsJackpotId;
	}

	public boolean isMilionarie() {
		return milionarie;
	}

	public void setMilionarie(boolean milionarie) {
		this.milionarie = milionarie;
	}

	public RealMillionvlt getRealMillionVlt() {
		return realMillionVlt;
	}

	public void setRealMillionVlt(RealMillionvlt realMillionVlt) {
		this.realMillionVlt = realMillionVlt;
	}

	@Override
	public String toString() {
		return "Meterfact [id=" + id + ", sistemagiocodim=" + sistemagiocodim
				+ ", tempodim=" + tempodim + ", clientedim=" + clientedim
				+ ", spaziodim=" + spaziodim + ", bet=" + bet + ", win=" + win
				+ ", gamesPlayed=" + gamesPlayed + ", jackpotWins="
				+ jackpotWins + ", jackpotContribution=" + jackpotContribution
				+ ", preu=" + preu + ", aams=" + aams + ", netWin=" + netWin
				+ ", houseWin=" + houseWin + ", supplierProfit="
				+ supplierProfit + ", operatorsProfit=" + operatorsProfit
				+ ", bplusNetProfit=" + bplusNetProfit + ", milionarie="
				+ milionarie + ", realMillionVlt=" + realMillionVlt
				+ ", aamsJackpotId=" + aamsJackpotId + "]";
	}


	

}
