package it.betplus.birs.primitive;

/**
 * Nazioni generated by hbm2java
 */
public class Nazione implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int idNazione;
	private String nome;

	public Nazione() {
	}

	public Nazione(int idNazione, String nome) {
		this.idNazione = idNazione;
		this.nome = nome;
	}



	public int getIdNazione() {
		return this.idNazione;
	}

	public void setIdNazione(int idNazione) {
		this.idNazione = idNazione;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + idNazione;
		result = prime * result + ((nome == null) ? 0 : nome.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Nazione other = (Nazione) obj;
		if (idNazione != other.idNazione)
			return false;
		if (nome == null) {
			if (other.nome != null)
				return false;
		} else if (!nome.equals(other.nome))
			return false;
		return true;
	}

}
