package it.betplus.birs.primitive;

/**
 * Province generated by hbm2java
 */
public class Provincia implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private String idProv;
	private Regione regione;
	private String nome;
	private String sigla;

	public Provincia() {
	}

	public Provincia(String idProv, Regione regione, String sigla) {
		this.idProv = idProv;
		this.regione = regione;
		this.sigla = sigla;
	}

	public Provincia(String idProv, Regione regione, String nome, String sigla) {
		this.idProv = idProv;
		this.regione = regione;
		this.nome = nome;
		this.sigla = sigla;
	}

	public String getIdProv() {
		return this.idProv;
	}

	public void setIdProv(String idProv) {
		this.idProv = idProv;
	}

	public Regione getRegioni() {
		return this.regione;
	}

	public void setRegioni(Regione regione) {
		this.regione = regione;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idProv == null) ? 0 : idProv.hashCode());
		result = prime * result + ((nome == null) ? 0 : nome.hashCode());
		result = prime * result + ((regione == null) ? 0 : regione.hashCode());
		result = prime * result + ((sigla == null) ? 0 : sigla.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Provincia other = (Provincia) obj;
		if (idProv == null) {
			if (other.idProv != null)
				return false;
		} else if (!idProv.equals(other.idProv))
			return false;
		if (nome == null) {
			if (other.nome != null)
				return false;
		} else if (!nome.equals(other.nome))
			return false;
		if (regione == null) {
			if (other.regione != null)
				return false;
		} else if (!regione.equals(other.regione))
			return false;
		if (sigla == null) {
			if (other.sigla != null)
				return false;
		} else if (!sigla.equals(other.sigla))
			return false;
		return true;
	}

}
