package it.betplus.birs.primitive;

/**
 * Regioni generated by hbm2java
 */
public class Regione implements java.io.Serializable {


	private static final long serialVersionUID = 1L;
	
	private int idReg;
	private Area area;
	private Nazione nazione;
	private String nome;

	public Regione() {
	}

	public Regione(int idReg, String nome) {
		this.idReg = idReg;
		this.nome = nome;
	}

	public Regione(int idReg, Area area, Nazione nazione, String nome) {
		this.idReg = idReg;
		this.area = area;
		this.nazione = nazione;
		this.nome = nome;
	}

	public int getIdReg() {
		return this.idReg;
	}

	public void setIdReg(int idReg) {
		this.idReg = idReg;
	}

	public Area getAree() {
		return this.area;
	}

	public void setAree(Area area) {
		this.area = area;
	}

	public Nazione getNazioni() {
		return this.nazione;
	}

	public void setNazioni(Nazione nazione) {
		this.nazione = nazione;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((area == null) ? 0 : area.hashCode());
		result = prime * result + idReg;
		result = prime * result + ((nazione == null) ? 0 : nazione.hashCode());
		result = prime * result + ((nome == null) ? 0 : nome.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Regione other = (Regione) obj;
		if (area == null) {
			if (other.area != null)
				return false;
		} else if (!area.equals(other.area))
			return false;
		if (idReg != other.idReg)
			return false;
		if (nazione == null) {
			if (other.nazione != null)
				return false;
		} else if (!nazione.equals(other.nazione))
			return false;
		if (nome == null) {
			if (other.nome != null)
				return false;
		} else if (!nome.equals(other.nome))
			return false;
		return true;
	}

	


}
