package it.betplus.birs.primitive;

// Generated 5-apr-2011 19.46.29 by Hibernate Tools 3.4.0.CR1


/**
 * Spaziodim generated by hbm2java
 */
public class Spaziodim implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	
	private long id;
	private Provincia provincia;
	private Regione regione;
	private Area area;
	private Comune comune;
	private Nazione nazione;

	public Spaziodim() {
		super();
	}

	public Spaziodim(long id, Provincia provincia, Regione regione,
			Area area, Comune comune, Nazione nazione) {
		this.id = id;
		this.provincia = provincia;
		this.regione = regione;
		this.area = area;
		this.comune = comune;
		this.nazione = nazione;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Provincia getProvincia() {
		return provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}

	public Regione getRegione() {
		return regione;
	}

	public void setRegione(Regione regione) {
		this.regione = regione;
	}

	public Area getArea() {
		return area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public Comune getComune() {
		return comune;
	}

	public void setComune(Comune comune) {
		this.comune = comune;
	}

	public Nazione getNazione() {
		return nazione;
	}

	public void setNazione(Nazione nazione) {
		this.nazione = nazione;
	}


	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((area == null) ? 0 : area.hashCode());
		result = prime * result + ((comune == null) ? 0 : comune.hashCode());
		result = prime * result + (int) (id ^ (id >>> 32));
		result = prime * result + ((nazione == null) ? 0 : nazione.hashCode());
		result = prime * result
				+ ((provincia == null) ? 0 : provincia.hashCode());
		result = prime * result + ((regione == null) ? 0 : regione.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Spaziodim other = (Spaziodim) obj;
		if (area == null) {
			if (other.area != null)
				return false;
		} else if (!area.equals(other.area))
			return false;
		if (comune == null) {
			if (other.comune != null)
				return false;
		} else if (!comune.equals(other.comune))
			return false;
		if (id != other.id)
			return false;
		if (nazione == null) {
			if (other.nazione != null)
				return false;
		} else if (!nazione.equals(other.nazione))
			return false;
		if (provincia == null) {
			if (other.provincia != null)
				return false;
		} else if (!provincia.equals(other.provincia))
			return false;
		if (regione == null) {
			if (other.regione != null)
				return false;
		} else if (!regione.equals(other.regione))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Spaziodim [id=" + id + ", provincia=" + provincia + ", regione="
				+ regione + ", area=" + area + ", comune=" + comune
				+ ", nazione=" + nazione + "]";
	}



}
